name: Middleman build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: ['3.1.2']
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Build
        run: bundle exec middleman build
        env:
          NO_CONTRACTS: "true"
